### ISSUE TITLE
detect generated classes to avoid annotating them with extended observability

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-agent#25]
Issue: We get non unique span names for generated classes.

We discussed this solution:

I can try this suggestion from Rafael
https://stackoverflow.com/questions/78643798/what-is-the-way-to-identify-generated-classes-in-bytebuddy-transformer/78649610#78649610
Stack OverflowStack Overflow
what is the way to identify generated classes in bytebuddy transformer
We have a bytebuddy transformer we install in a javaagent something like that:
new AgentBuilder.Default()
.type(TypeMatchers.create(Configuration.getInstance()))

**Comment by shalom938** [comment]
the solution is for simple generated classes like this:
https://github.com/digma-ai/digma-agent/blob/3f9518486d698718130954c25312a6549d2c44a4/src/test/java/org/digma/GeneratedClassMatchersTests.java

and for spring data PersistentPropertyAccessor and ObjectInstantiator, this solves the issue with spring elastic search.
there may be many more types that spring generates,its not possible to detect then generally because the way spring generates them they look like regular classes.
the way to support all generated spring classes is to research all spring framework and figure out all the types that spring generates and add exclude matchers. or wait for issues from users and solve them one by one.
